name: Keep DB Alive
on:
  schedule:
    - cron: '*/20 * * * *'  # every 20 minutes
  workflow_dispatch: 
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping site
        run: curl -s https://cakeshop-app-g7anhrf8hwcwfeep.canadaeast-01.azurewebsites.net/api/v1/menu > /dev/null
